CREATE TABLE `idea_outcomes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text NOT NULL,
	`category` varchar(100),
	`budget` decimal(15,2),
	`teamSize` int,
	`timelineMonths` int,
	`marketDemand` decimal(5,2),
	`technicalFeasibility` decimal(5,2),
	`competitiveAdvantage` decimal(5,2),
	`userEngagement` decimal(5,2),
	`tagsCount` int,
	`hypothesisValidationRate` decimal(5,2),
	`ratCompletionRate` decimal(5,2),
	`outcome` enum('success','failure','pending') NOT NULL DEFAULT 'pending',
	`outcomeDate` timestamp,
	`outcomeNotes` text,
	`classifiedBy` int,
	`classifiedAt` timestamp,
	`predictedSuccessRate` decimal(5,2),
	`predictionModel` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `idea_outcomes_id` PRIMARY KEY(`id`)
);
