CREATE TABLE `classification_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ideaId` int NOT NULL,
	`analysisId` int NOT NULL,
	`classification` enum('innovation','commercial','weak') NOT NULL,
	`overallScore` decimal(5,2) NOT NULL,
	`userFeedback` enum('accepted','appealed','revised','abandoned'),
	`feedbackNotes` text,
	`appealReason` text,
	`appealStatus` enum('none','pending','approved','rejected') DEFAULT 'none',
	`appealReviewedBy` int,
	`appealReviewedAt` timestamp,
	`appealNotes` text,
	`revisionNumber` int DEFAULT 1,
	`previousClassification` enum('innovation','commercial','weak'),
	`classifiedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `classification_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `evaluation_criteria` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`nameEn` varchar(100),
	`description` text,
	`descriptionEn` text,
	`weight` decimal(5,2) NOT NULL,
	`guidelines` json,
	`examples` json,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `evaluation_criteria_id` PRIMARY KEY(`id`),
	CONSTRAINT `evaluation_criteria_name_unique` UNIQUE(`name`)
);
--> statement-breakpoint
CREATE TABLE `idea_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ideaId` int NOT NULL,
	`overallScore` decimal(5,2) NOT NULL,
	`classification` enum('innovation','commercial','weak') NOT NULL,
	`noveltyScore` decimal(5,2) NOT NULL,
	`impactScore` decimal(5,2) NOT NULL,
	`feasibilityScore` decimal(5,2) NOT NULL,
	`commercialScore` decimal(5,2) NOT NULL,
	`scalabilityScore` decimal(5,2) NOT NULL,
	`sustainabilityScore` decimal(5,2) NOT NULL,
	`aiAnalysis` text,
	`strengths` json,
	`weaknesses` json,
	`opportunities` json,
	`threats` json,
	`recommendations` json,
	`nextSteps` json,
	`similarInnovations` json,
	`extractedKeywords` json,
	`sentimentScore` decimal(5,2),
	`complexityLevel` enum('low','medium','high','very_high'),
	`marketSize` varchar(100),
	`competitionLevel` enum('low','medium','high','very_high'),
	`marketTrends` json,
	`status` enum('pending','completed','failed') DEFAULT 'pending',
	`processingTime` int,
	`analyzedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `idea_analysis_id` PRIMARY KEY(`id`),
	CONSTRAINT `idea_analysis_ideaId_unique` UNIQUE(`ideaId`)
);
--> statement-breakpoint
CREATE TABLE `ideas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(500) NOT NULL,
	`titleEn` varchar(500),
	`description` text NOT NULL,
	`descriptionEn` text,
	`problem` text,
	`solution` text,
	`targetMarket` text,
	`uniqueValue` text,
	`category` varchar(100),
	`subCategory` varchar(100),
	`keywords` json,
	`documents` json,
	`images` json,
	`status` enum('draft','submitted','analyzing','analyzed','revision_needed','approved','commercial') DEFAULT 'draft',
	`analysisId` int,
	`submittedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ideas_id` PRIMARY KEY(`id`)
);
