import assert from "node:assert/strict";
import mysql from "mysql2/promise";

const url = process.env.NAQLA_TEST_DATABASE_URL; if (!url) throw new Error("REFUSE_UNISOLATED_DATABASE");
const parsed = new URL(url); if (parsed.hostname !== "127.0.0.1" || !/^\/naqla_phase3_test_[a-z0-9]+$/.test(parsed.pathname)) throw new Error("REFUSE_UNISOLATED_DATABASE");
process.env.NODE_ENV = "test"; process.env.DATABASE_URL = url; process.env.AI_EXTERNAL_PROVIDER_ENABLED = "false";
type Envelope = { result?: { data?: { json?: unknown } }; error?: { json?: { data?: { code?: string }; message?: string } } };
const ok = <T>(body: Envelope) => { assert.ok(body.result?.data, body.error?.json?.message); return body.result.data.json as T; };
const id = { owner: 731001, counterparty: 731002, foreign: 731003, ownerOrg: 831001, counterpartyOrg: 831002, foreignOrg: 831003, record: 931001, version: 931002, engagement: 931003, authorizedEvidence: 931005, revokedEvidence: 931006 };
let connection: mysql.Connection | undefined; let server: import("node:http").Server | undefined;
try {
  connection = await mysql.createConnection(url); const at = "2026-08-24 00:00:00";
  await connection.query("INSERT INTO users (id,openId,name,email,role,createdAt,updatedAt,lastSignedIn) VALUES ?", [[[id.owner,"p3-owner","Synthetic Owner","p3-owner@example.invalid","user",at,at,at],[id.counterparty,"p3-counterparty","Synthetic Counterparty","p3-counterparty@example.invalid","user",at,at,at],[id.foreign,"p3-foreign","Synthetic Foreign","p3-foreign@example.invalid","user",at,at,at]]]);
  await connection.query("INSERT INTO organizations (id,nameAr,nameEn,type,scope,createdAt,updatedAt) VALUES ?", [[[id.ownerOrg,"منظمة مالك تركيبية","Synthetic Owner Org","private","local",at,at],[id.counterpartyOrg,"منظمة طرف تركيبية","Synthetic Counterparty Org","private","local",at,at],[id.foreignOrg,"منظمة أجنبية","Synthetic Foreign Org","private","local",at,at]]]);
  await connection.query("INSERT INTO organization_memberships (organizationId,userId,role,status,createdAt,updatedAt) VALUES ?", [[[id.ownerOrg,id.owner,"owner","active",at,at],[id.counterpartyOrg,id.counterparty,"member","active",at,at],[id.foreignOrg,id.foreign,"member","active",at,at]]]);
  await connection.query("INSERT INTO user_active_contexts (userId,organizationId,updatedAt) VALUES ?", [[[id.owner,id.ownerOrg,at],[id.counterparty,id.counterpartyOrg,at],[id.foreign,id.foreignOrg,at]]]);
  await connection.query("INSERT INTO naqla1_innovation_records (id,owner_user_id,title,problem_statement,desired_outcome,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)", [id.record,id.owner,"Synthetic qualified record","Synthetic commercial problem","Synthetic commercial outcome","qualified",at,at]);
  await connection.query("INSERT INTO naqla1_immutable_versions (id,innovation_record_id,owner_user_id,version_number,snapshot_sha256,created_at) VALUES (?,?,?,?,?,?)", [id.version,id.record,id.owner,1,"a".repeat(64),at]);
  await connection.query("INSERT INTO naqla1_evidence (id,innovation_record_id,owner_user_id,label,evidence_type,content_sha256,authorization_status,created_at,revoked_at) VALUES ?", [[[id.authorizedEvidence,id.record,id.owner,"Synthetic authorized evidence","synthetic_note","b".repeat(64),"authorized",at,null],[id.revokedEvidence,id.record,id.owner,"Synthetic revoked evidence","synthetic_note","c".repeat(64),"revoked",at,at]]]);
  await connection.query("INSERT INTO naqla2_engagements (id,interest_request_id,owner_user_id,requester_user_id,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)", [id.engagement,931004,id.owner,id.counterparty,"established",at,at]);
  const { createApp } = await import("../server/_core/index.ts"); const composed = await createApp({ serveFrontend: false }); server = composed.server; await new Promise<void>(resolve => server!.listen(0,"127.0.0.1",resolve)); const address = server.address(); assert.ok(address && typeof address !== "string"); const base = `http://127.0.0.1:${address.port}`;
  const call = async (kind: "query" | "mutation", procedure: string, input: unknown, userId?: number) => { const inputJson = JSON.stringify({ json: input }); const headers = userId ? { "x-naqla-test-user-id": String(userId) } : {}; const response = kind === "query" ? await fetch(`${base}/api/trpc/${procedure}?input=${encodeURIComponent(inputJson)}`, { headers }) : await fetch(`${base}/api/trpc/${procedure}`, { method:"POST",headers:{"content-type":"application/json",...headers},body:inputJson }); return { response, body: await response.json() as Envelope }; };
  const unauth = await call("mutation","naqla3.commercialize.createAsset",{sourceInnovationRecordId:id.record,sourceInnovationRecordVersion:1,title:"Bad",summary:"Synthetic unauthorized request must not persist.",assetType:"technology",classification:"restricted",evidenceIds:[]}); assert.equal(unauth.response.status,401);
  const source = ok<Array<{ id:number; versionNumber:number }>>((await call("query","naqla3.commercialize.listEligibleInnovationSources",null,id.owner)).body)[0]!; assert.equal(source.id,id.record);
  const assetInput={sourceInnovationRecordId:source.id,sourceInnovationRecordVersion:source.versionNumber,title:"Synthetic commercial asset",summary:"Synthetic governed commercial value proposition for isolated HTTP testing.",assetType:"technology",classification:"restricted",evidenceIds:[id.authorizedEvidence]}; const asset = ok<{assetId:number}>((await call("mutation","naqla3.commercialize.createAsset",assetInput,id.owner)).body); const revoked = await call("mutation","naqla3.commercialize.createAsset",{...assetInput,title:"Revoked evidence must fail",evidenceIds:[id.revokedEvidence]},id.owner); assert.equal(revoked.response.status,403); const versioned = ok<{versionNumber:number}>((await call("mutation","naqla3.commercialize.createAssetVersion",{assetId:asset.assetId,summary:"Synthetic commercial asset revision with reauthorized evidence reference.",evidenceIds:[id.authorizedEvidence]},id.owner)).body); assert.equal(versioned.versionNumber,2); assert.equal(ok<Array<{versionNumber:number}>>((await call("query","naqla3.commercialize.listAssetVersions",{assetId:asset.assetId},id.owner)).body).length,2); assert.equal(ok<{version:number}>((await call("mutation","naqla3.commercialize.createReadinessVersion",{assetId:asset.assetId,checklist:[{key:"human-review",complete:false}]},id.owner)).body).version,2);
  const createInput={assetId:asset.assetId,counterpartyUserId:id.counterparty,counterpartyOrganizationId:id.counterpartyOrg,engagementId:id.engagement,idempotencyKey:"phase3-transaction-0001"}; const transaction=ok<{transactionId:number;reused:boolean}>((await call("mutation","naqla3.commercialize.createTransaction",createInput,id.owner)).body); assert.equal(transaction.reused,false); assert.equal(ok<{reused:boolean}>((await call("mutation","naqla3.commercialize.createTransaction",createInput,id.owner)).body).reused,true);
  assert.equal((await call("query","naqla3.commercialize.getTransactionWorkspace",{transactionId:transaction.transactionId},id.foreign)).response.status,403); assert.equal(ok<{transaction:{id:number}}>((await call("query","naqla3.commercialize.getTransactionWorkspace",{transactionId:transaction.transactionId},id.counterparty)).body).transaction.id,transaction.transactionId);
  const dd=ok<{caseId:number}>((await call("mutation","naqla3.commercialize.createDueDiligenceCase",{transactionId:transaction.transactionId,checklist:[{key:"scope",complete:true}]},id.owner)).body); const req=ok<{requestId:number}>((await call("mutation","naqla3.commercialize.createDueDiligenceRequest",{caseId:dd.caseId,transactionId:transaction.transactionId,recipientUserId:id.counterparty,subject:"Synthetic request",body:"Please confirm the synthetic delivery boundary.",idempotencyKey:"phase3-dd-request-0001"},id.owner)).body); assert.equal(ok<{status:string}>((await call("mutation","naqla3.commercialize.respondDueDiligenceRequest",{requestId:req.requestId,responseBody:"Synthetic counterparty response confirmed by a human.",},id.counterparty)).body).status,"responded"); await call("mutation","naqla3.commercialize.completeDueDiligence",{caseId:dd.caseId,transactionId:transaction.transactionId,confirmationNote:"Synthetic human completion."},id.owner);
  let version=1; for (const stage of ["due_diligence","contract"] as const) { const moved=ok<{stage:string;transitionVersion:number}>((await call("mutation","naqla3.commercialize.transitionStage",{transactionId:transaction.transactionId,toStage:stage,expectedTransitionVersion:version,idempotencyKey:`phase3-stage-${stage}-001`},id.owner)).body); assert.equal(moved.stage,stage); version=moved.transitionVersion; }
  const terms=ok<{termSheetId:number}>((await call("mutation","naqla3.commercialize.createTermSheet",{transactionId:transaction.transactionId,commercialScope:"Synthetic human-reviewed commercial scope.",structure:"Synthetic human-reviewed transaction structure."},id.owner)).body); const agreement=ok<{agreementId:number}>((await call("mutation","naqla3.commercialize.createAgreementRecord",{transactionId:transaction.transactionId,termSheetId:terms.termSheetId,title:"Synthetic agreement record"},id.owner)).body); assert.equal(ok<{status:string}>((await call("mutation","naqla3.commercialize.setAgreementExecutionStatus",{agreementId:agreement.agreementId,status:"executed",externalReference:"SYNTHETIC-REF"},id.owner)).body).status,"executed");
  let moved=ok<{stage:string;transitionVersion:number}>((await call("mutation","naqla3.commercialize.transitionStage",{transactionId:transaction.transactionId,toStage:"execute",expectedTransitionVersion:version,idempotencyKey:"phase3-stage-execute-001"},id.owner)).body); version=moved.transitionVersion; assert.equal(moved.stage,"execute"); await call("mutation","naqla3.commercialize.createExecutionPlan",{transactionId:transaction.transactionId,objectives:"Synthetic governed execution objective with human accountability."},id.owner); moved=ok<{stage:string;transitionVersion:number}>((await call("mutation","naqla3.commercialize.transitionStage",{transactionId:transaction.transactionId,toStage:"scale",expectedTransitionVersion:version,idempotencyKey:"phase3-stage-scale-001"},id.owner)).body); assert.equal(moved.stage,"scale"); assert.equal(ok<{outcome:string}>((await call("mutation","naqla3.commercialize.recordScaleDecision",{transactionId:transaction.transactionId,outcome:"continue_limited",lessonsLearned:"Synthetic human-recorded lessons learned."},id.owner)).body).outcome,"continue_limited");
  const document=ok<{documentId:number}>((await call("mutation","naqla3.commercialize.registerDataRoomDocument",{transactionId:transaction.transactionId,documentType:"evidence",title:"Synthetic controlled document",storageKey:"synthetic/no-real-file",mimeType:"text/plain",sizeBytes:12,classification:"confidential"},id.owner)).body); assert.equal(ok<unknown[]>((await call("query","naqla3.commercialize.listDataRoomDocuments",{transactionId:transaction.transactionId},id.counterparty)).body).length,0); await call("mutation","naqla3.commercialize.shareDataRoomDocument",{documentId:document.documentId,granteeUserId:id.counterparty,granteeOrganizationId:id.counterpartyOrg,allowedRoles:["counterparty"]},id.owner); const docs=ok<Array<Record<string,unknown>>>((await call("query","naqla3.commercialize.listDataRoomDocuments",{transactionId:transaction.transactionId},id.counterparty)).body); assert.equal(docs.length,1); assert.equal("storageKey" in docs[0]!,false); await call("mutation","naqla3.commercialize.revokeDataRoomDocumentShare",{documentId:document.documentId,granteeUserId:id.counterparty,granteeOrganizationId:id.counterpartyOrg},id.owner); assert.equal(ok<unknown[]>((await call("query","naqla3.commercialize.listDataRoomDocuments",{transactionId:transaction.transactionId},id.counterparty)).body).length,0);
  const [audits] = await connection.query<mysql.RowDataPacket[]>("SELECT COUNT(*) AS count FROM naqla3_commercial_action_logs WHERE transactionId=?",[transaction.transactionId]); assert.ok(Number(audits[0]?.count)>=7); console.log(JSON.stringify({phase:"NAQLA3",synthetic:true,transport:"express-trpc-http",commercialJourney:"PASS",tenantIsolation:"PASS",dataRoomRevocation:"PASS",idempotency:"PASS",auditCount:Number(audits[0]?.count),externalProviderCalls:0}));
} finally { if (server) await new Promise<void>(resolve=>server!.close(()=>resolve())); const { closeDbForTesting }=await import("../server/db.ts"); await closeDbForTesting(); if(connection) await connection.end(); }
