import { TRPCError } from "@trpc/server";
import { and, desc, eq, inArray, sql } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";
import { naqla1Evidence, naqla1ImmutableVersions, naqla1InnovationRecords, naqla2Engagements, naqla3CommercialAssets, naqla3CommercialTransactions, organizationMemberships, userActiveContexts } from "../../drizzle/schema";

const stages = ["prepare", "due_diligence", "contract", "execute", "scale"] as const;
type Stage = typeof stages[number];
const now = () => new Date().toISOString().slice(0, 19).replace("T", " ");
const capabilities = ["view_asset", "manage_asset", "create_transaction", "view_transaction", "manage_due_diligence", "request_information", "respond_due_diligence", "access_data_room", "manage_data_room", "manage_terms", "manage_execution", "close_transaction", "manage_participants"] as const;
const capabilitySchema = z.enum(capabilities);
type Row = Record<string, unknown>;
type Header = { insertId?: number; affectedRows?: number };
const rows = async (database: NonNullable<Awaited<ReturnType<typeof getDb>>>, statement: ReturnType<typeof sql>) => (await database.execute(statement) as unknown as [Row[], unknown])[0];
const header = async (database: NonNullable<Awaited<ReturnType<typeof getDb>>>, statement: ReturnType<typeof sql>) => (await database.execute(statement) as unknown as [Header, unknown])[0];

async function context(database: NonNullable<Awaited<ReturnType<typeof getDb>>>, userId: number) {
  const [active] = await database.select().from(userActiveContexts).where(eq(userActiveContexts.userId, userId)).limit(1);
  if (!active?.organizationId) throw new TRPCError({ code: "FORBIDDEN", message: "ACTIVE_CONTEXT_REQUIRED" });
  const [membership] = await database.select().from(organizationMemberships).where(and(eq(organizationMemberships.organizationId, active.organizationId), eq(organizationMemberships.userId, userId), eq(organizationMemberships.status, "active"))).limit(1);
  if (!membership) throw new TRPCError({ code: "FORBIDDEN", message: "ACTIVE_MEMBERSHIP_REQUIRED" });
  return { organizationId: active.organizationId, membership };
}
async function participant(database: NonNullable<Awaited<ReturnType<typeof getDb>>>, transactionId: number, userId: number, capability?: typeof capabilities[number]) {
  const active = await context(database, userId);
  const found = await rows(database, sql`SELECT * FROM naqla3_transaction_participants WHERE transactionId=${transactionId} AND userId=${userId} AND tenantId=${active.organizationId} AND status='active' LIMIT 1`);
  const entry = found[0];
  if (!entry) throw new TRPCError({ code: "FORBIDDEN", message: "TRANSACTION_PARTICIPANT_REQUIRED" });
  const granted = Array.isArray(entry.capabilities) ? entry.capabilities : typeof entry.capabilities === "string" ? JSON.parse(entry.capabilities) : [];
  if (capability && !granted.includes(capability)) throw new TRPCError({ code: "FORBIDDEN", message: "COMMERCIAL_CAPABILITY_REQUIRED" });
  return { active, entry, granted: granted as string[] };
}
async function log(database: NonNullable<Awaited<ReturnType<typeof getDb>>>, actorUserId: number, action: string, data: { transactionId?: number; assetId?: number; idempotencyKey?: string; metadata?: Record<string, unknown> }) {
  await header(database, sql`INSERT INTO naqla3_commercial_action_logs (transactionId,assetId,actorUserId,action,idempotencyKey,safeMetadata) VALUES (${data.transactionId ?? null},${data.assetId ?? null},${actorUserId},${action},${data.idempotencyKey ?? null},${JSON.stringify(data.metadata ?? {})})`);
}
function requireNext(current: string | null, next: Stage) { const index = stages.indexOf((current ?? "prepare") as Stage); if (index < 0 || stages[index + 1] !== next) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "INVALID_COMMERCIAL_STAGE_TRANSITION" }); }

export const commercializeRouter = router({
  listEligibleInnovationSources: protectedProcedure.query(async ({ ctx }) => {
    const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await context(database, ctx.user.id);
    const records = await database.select().from(naqla1InnovationRecords).where(and(eq(naqla1InnovationRecords.ownerUserId, ctx.user.id), eq(naqla1InnovationRecords.status, "qualified"))).orderBy(desc(naqla1InnovationRecords.updatedAt));
    const result: Array<{ id: number; title: string; versionId: number; versionNumber: number }> = [];
    for (const record of records) { const [version] = await database.select().from(naqla1ImmutableVersions).where(and(eq(naqla1ImmutableVersions.innovationRecordId, record.id), eq(naqla1ImmutableVersions.ownerUserId, ctx.user.id))).orderBy(desc(naqla1ImmutableVersions.versionNumber)).limit(1); if (version) result.push({ id: record.id, title: record.title, versionId: version.id, versionNumber: version.versionNumber }); }
    return result;
  }),
  listEligibleEngagements: protectedProcedure.query(async ({ ctx }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await context(database, ctx.user.id); const engagements = await database.select().from(naqla2Engagements).where(eq(naqla2Engagements.status, "established")); const result: Array<{ id: number; counterpartyUserId: number; counterpartyOrganizationId: number }> = []; for (const engagement of engagements) { if (engagement.ownerUserId !== ctx.user.id && engagement.requesterUserId !== ctx.user.id) continue; const counterpartyUserId = engagement.ownerUserId === ctx.user.id ? engagement.requesterUserId : engagement.ownerUserId; const [membership] = await database.select().from(organizationMemberships).where(and(eq(organizationMemberships.userId, counterpartyUserId), eq(organizationMemberships.status, "active"))).limit(1); if (membership) result.push({ id: engagement.id, counterpartyUserId, counterpartyOrganizationId: membership.organizationId }); } return result; }),
  createAsset: protectedProcedure.input(z.object({ sourceInnovationRecordId: z.number().int(), sourceInnovationRecordVersion: z.number().int().positive(), title: z.string().trim().min(3).max(500), summary: z.string().trim().min(20).max(12000), assetType: z.string().trim().min(2).max(80), classification: z.enum(["restricted", "confidential"]), evidenceIds: z.array(z.number().int()).max(100).default([]) }).strict()).mutation(async ({ ctx, input }) => {
    const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const active = await context(database, ctx.user.id);
    const [record] = await database.select().from(naqla1InnovationRecords).where(and(eq(naqla1InnovationRecords.id, input.sourceInnovationRecordId), eq(naqla1InnovationRecords.ownerUserId, ctx.user.id), eq(naqla1InnovationRecords.status, "qualified"))).limit(1);
    if (!record) throw new TRPCError({ code: "NOT_FOUND", message: "QUALIFIED_INNOVATION_REQUIRED" });
    const [source] = await database.select().from(naqla1ImmutableVersions).where(and(eq(naqla1ImmutableVersions.innovationRecordId, record.id), eq(naqla1ImmutableVersions.versionNumber, input.sourceInnovationRecordVersion), eq(naqla1ImmutableVersions.ownerUserId, ctx.user.id))).limit(1);
    if (!source) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "PINNED_SOURCE_VERSION_REQUIRED" });
    if (input.evidenceIds.length) {
      const evidence = await database.select({ id: naqla1Evidence.id }).from(naqla1Evidence).where(and(eq(naqla1Evidence.innovationRecordId, record.id), eq(naqla1Evidence.ownerUserId, ctx.user.id), eq(naqla1Evidence.authorizationStatus, "authorized"), inArray(naqla1Evidence.id, input.evidenceIds)));
      if (evidence.length !== new Set(input.evidenceIds).size) throw new TRPCError({ code: "FORBIDDEN", message: "EVIDENCE_REAUTHORIZATION_REQUIRED" });
    }
    const created = await database.insert(naqla3CommercialAssets).values({ ownerUserId: ctx.user.id, tenantId: active.organizationId, sourceInnovationRecordId: record.id, sourceInnovationRecordVersion: source.versionNumber, sourceSnapshotHash: source.snapshotSha256, title: input.title, scope: input.summary, summary: input.summary, assetType: input.assetType, classification: input.classification, status: "prepared" }).$returningId();
    const assetId = created[0]!.id;
    const assetVersion = await header(database, sql`INSERT INTO naqla3_commercial_asset_versions (assetId,tenantId,versionNumber,summary,evidenceSnapshot,sourceSnapshotHash,createdBy) VALUES (${assetId},${active.organizationId},1,${input.summary},${JSON.stringify(input.evidenceIds)},${source.snapshotSha256},${ctx.user.id})`);
    await header(database, sql`INSERT INTO naqla3_commercial_readiness_assessments (assetId,tenantId,version,status,checklist,gapSummary,createdBy) VALUES (${assetId},${active.organizationId},1,'ready_for_discussion',${JSON.stringify([{ key: "pinned_innovation", complete: true }, { key: "human_review_required", complete: false }])},${JSON.stringify([])},${ctx.user.id})`);
    await log(database, ctx.user.id, "asset_created", { assetId, metadata: { sourceInnovationRecordId: record.id, sourceVersion: source.versionNumber } });
    return { assetId, assetVersionId: Number(assetVersion.insertId), readiness: "ready_for_discussion" };
  }),
  listAssets: protectedProcedure.query(async ({ ctx }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const active = await context(database, ctx.user.id); return database.select().from(naqla3CommercialAssets).where(and(eq(naqla3CommercialAssets.ownerUserId, ctx.user.id), eq(naqla3CommercialAssets.tenantId, active.organizationId))).orderBy(desc(naqla3CommercialAssets.updatedAt)); }),
  listAssetVersions: protectedProcedure.input(z.object({ assetId: z.number().int() }).strict()).query(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const active = await context(database, ctx.user.id); const [asset] = await database.select().from(naqla3CommercialAssets).where(and(eq(naqla3CommercialAssets.id, input.assetId), eq(naqla3CommercialAssets.ownerUserId, ctx.user.id), eq(naqla3CommercialAssets.tenantId, active.organizationId))).limit(1); if (!asset) throw new TRPCError({ code: "NOT_FOUND" }); return rows(database, sql`SELECT id,versionNumber,summary,evidenceSnapshot,sourceSnapshotHash,createdBy,createdAt FROM naqla3_commercial_asset_versions WHERE assetId=${input.assetId} AND tenantId=${active.organizationId} ORDER BY versionNumber DESC`); }),
  createAssetVersion: protectedProcedure.input(z.object({ assetId: z.number().int(), summary: z.string().trim().min(20).max(12000), evidenceIds: z.array(z.number().int()).max(100).default([]) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const active = await context(database, ctx.user.id); const [asset] = await database.select().from(naqla3CommercialAssets).where(and(eq(naqla3CommercialAssets.id, input.assetId), eq(naqla3CommercialAssets.ownerUserId, ctx.user.id), eq(naqla3CommercialAssets.tenantId, active.organizationId))).limit(1); if (!asset) throw new TRPCError({ code: "NOT_FOUND" }); if (input.evidenceIds.length) { const evidence = await database.select({ id: naqla1Evidence.id }).from(naqla1Evidence).where(and(eq(naqla1Evidence.innovationRecordId, asset.sourceInnovationRecordId!), eq(naqla1Evidence.ownerUserId, ctx.user.id), eq(naqla1Evidence.authorizationStatus, "authorized"), inArray(naqla1Evidence.id, input.evidenceIds))); if (evidence.length !== new Set(input.evidenceIds).size) throw new TRPCError({ code: "FORBIDDEN", message: "EVIDENCE_REAUTHORIZATION_REQUIRED" }); }
    const latest = (await rows(database, sql`SELECT COALESCE(MAX(versionNumber),0) AS currentVersion FROM naqla3_commercial_asset_versions WHERE assetId=${asset.id}`))[0]; const versionNumber = Number(latest?.currentVersion ?? 0) + 1; const hash = `${asset.sourceSnapshotHash}:${versionNumber}`; const result = await header(database, sql`INSERT INTO naqla3_commercial_asset_versions (assetId,tenantId,versionNumber,summary,evidenceSnapshot,sourceSnapshotHash,createdBy) VALUES (${asset.id},${active.organizationId},${versionNumber},${input.summary},${JSON.stringify(input.evidenceIds)},${hash},${ctx.user.id})`); await log(database, ctx.user.id, "asset_version_created", { assetId: asset.id, metadata: { versionNumber, evidenceCount: input.evidenceIds.length } }); return { assetVersionId: Number(result.insertId), versionNumber }; }),
  listReadinessVersions: protectedProcedure.input(z.object({ assetId: z.number().int() }).strict()).query(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const active = await context(database, ctx.user.id); return rows(database, sql`SELECT r.id,r.version,r.status,r.checklist,r.gapSummary,r.createdAt FROM naqla3_commercial_readiness_assessments r INNER JOIN naqla3_commercial_assets a ON a.id=r.assetId WHERE r.assetId=${input.assetId} AND r.tenantId=${active.organizationId} AND a.ownerUserId=${ctx.user.id} ORDER BY r.version DESC`); }),
  createReadinessVersion: protectedProcedure.input(z.object({ assetId: z.number().int(), checklist: z.array(z.object({ key: z.string().min(2), complete: z.boolean() })).min(1).max(40) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const active = await context(database, ctx.user.id); const [asset] = await database.select().from(naqla3CommercialAssets).where(and(eq(naqla3CommercialAssets.id, input.assetId), eq(naqla3CommercialAssets.ownerUserId, ctx.user.id), eq(naqla3CommercialAssets.tenantId, active.organizationId))).limit(1); if (!asset) throw new TRPCError({ code: "NOT_FOUND" }); const version = Number((await rows(database, sql`SELECT COALESCE(MAX(version),0) AS currentVersion FROM naqla3_commercial_readiness_assessments WHERE assetId=${asset.id}`))[0]?.currentVersion ?? 0) + 1; const gaps = input.checklist.filter(item => !item.complete).map(item => item.key); const status = gaps.length ? "needs_human_follow_up" : "ready_for_discussion"; const result = await header(database, sql`INSERT INTO naqla3_commercial_readiness_assessments (assetId,tenantId,version,status,checklist,gapSummary,createdBy) VALUES (${asset.id},${active.organizationId},${version},${status},${JSON.stringify(input.checklist)},${JSON.stringify(gaps)},${ctx.user.id})`); await log(database, ctx.user.id, "readiness_version_created", { assetId: asset.id, metadata: { version, status } }); return { readinessId: Number(result.insertId), version, status }; }),
  createTransaction: protectedProcedure.input(z.object({ assetId: z.number().int(), counterpartyUserId: z.number().int(), counterpartyOrganizationId: z.number().int(), engagementId: z.number().int(), idempotencyKey: z.string().min(12).max(160) }).strict()).mutation(async ({ ctx, input }) => {
    const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const active = await context(database, ctx.user.id);
    const [asset] = await database.select().from(naqla3CommercialAssets).where(and(eq(naqla3CommercialAssets.id, input.assetId), eq(naqla3CommercialAssets.ownerUserId, ctx.user.id), eq(naqla3CommercialAssets.tenantId, active.organizationId))).limit(1); if (!asset) throw new TRPCError({ code: "NOT_FOUND", message: "COMMERCIAL_ASSET_NOT_FOUND" });
    const existing = await rows(database, sql`SELECT id FROM naqla3_commercial_transactions WHERE idempotencyKey=${input.idempotencyKey} AND initiatorUserId=${ctx.user.id} LIMIT 1`); if (existing[0]) return { transactionId: Number(existing[0].id), reused: true, stage: "prepare" };
    const [engagement] = await database.select().from(naqla2Engagements).where(and(eq(naqla2Engagements.id, input.engagementId), eq(naqla2Engagements.status, "established"))).limit(1); if (!engagement || ![engagement.ownerUserId, engagement.requesterUserId].includes(ctx.user.id) || ![engagement.ownerUserId, engagement.requesterUserId].includes(input.counterpartyUserId)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "ESTABLISHED_ENGAGEMENT_REQUIRED" });
    const inserted = await database.insert(naqla3CommercialTransactions).values({ assetId: asset.id, engagementId: engagement.id, initiatorUserId: ctx.user.id, counterpartyUserId: input.counterpartyUserId, tenantId: active.organizationId, origin: "engagement", stage: "prepare", ownerUserId: ctx.user.id, policyVersion: "naqla3-commercialize-v1", startedAt: now(), transitionVersion: 1, idempotencyKey: input.idempotencyKey, status: "active" }).$returningId(); const transactionId = inserted[0]!.id;
    const ownerCapabilities = capabilities; const counterpartyCapabilities = ["view_transaction", "respond_due_diligence", "access_data_room"];
    await header(database, sql`INSERT INTO naqla3_transaction_participants (transactionId,tenantId,userId,organizationId,role,capabilities,createdBy) VALUES (${transactionId},${active.organizationId},${ctx.user.id},${active.organizationId},'owner',${JSON.stringify(ownerCapabilities)},${ctx.user.id}),(${transactionId},${input.counterpartyOrganizationId},${input.counterpartyUserId},${input.counterpartyOrganizationId},'counterparty',${JSON.stringify(counterpartyCapabilities)},${ctx.user.id})`);
    await log(database, ctx.user.id, "transaction_created", { transactionId, assetId: asset.id, idempotencyKey: input.idempotencyKey }); return { transactionId, reused: false, stage: "prepare" };
  }),
  getTransactionWorkspace: protectedProcedure.input(z.object({ transactionId: z.number().int() }).strict()).query(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const access = await participant(database, input.transactionId, ctx.user.id, "view_transaction"); const transaction = (await rows(database, sql`SELECT id,assetId,stage,status,transitionVersion,outcome FROM naqla3_commercial_transactions WHERE id=${input.transactionId} LIMIT 1`))[0]; if (!transaction) throw new TRPCError({ code: "NOT_FOUND" }); const dd = (await rows(database, sql`SELECT id,status,checklist FROM naqla3_due_diligence_cases WHERE transactionId=${input.transactionId} LIMIT 1`))[0] ?? null; const term = (await rows(database, sql`SELECT id,status,versionNumber FROM naqla3_term_sheets WHERE transactionId=${input.transactionId} ORDER BY id DESC LIMIT 1`))[0] ?? null; return { transaction, participant: { role: access.entry.role, capabilities: access.granted }, dueDiligence: dd, termSheet: term, nextBestAction: { text: `Complete the authorized human action for ${(transaction.stage as string) ?? "prepare"}.` } }; }),
  listTransactionParticipants: protectedProcedure.input(z.object({ transactionId: z.number().int() }).strict()).query(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await participant(database, input.transactionId, ctx.user.id, "view_transaction"); return rows(database, sql`SELECT userId,organizationId,role FROM naqla3_transaction_participants WHERE transactionId=${input.transactionId} AND status='active'`); }),
  createDueDiligenceCase: protectedProcedure.input(z.object({ transactionId: z.number().int(), checklist: z.array(z.object({ key: z.string(), complete: z.boolean() })).min(1) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const access = await participant(database, input.transactionId, ctx.user.id, "manage_due_diligence"); const result = await header(database, sql`INSERT INTO naqla3_due_diligence_cases (transactionId,tenantId,status,checklist,createdBy) VALUES (${input.transactionId},${access.active.organizationId},'open',${JSON.stringify(input.checklist)},${ctx.user.id})`); await log(database, ctx.user.id, "due_diligence_created", { transactionId: input.transactionId }); return { caseId: Number(result.insertId), status: "open" }; }),
  createDueDiligenceRequest: protectedProcedure.input(z.object({ caseId: z.number().int(), transactionId: z.number().int(), recipientUserId: z.number().int(), subject: z.string().min(3), body: z.string().min(10), idempotencyKey: z.string().min(12) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await participant(database, input.transactionId, ctx.user.id, "request_information"); const existing = (await rows(database, sql`SELECT id FROM naqla3_due_diligence_requests WHERE idempotencyKey=${input.idempotencyKey} LIMIT 1`))[0]; if (existing) return { requestId: Number(existing.id), reused: true }; const result = await header(database, sql`INSERT INTO naqla3_due_diligence_requests (caseId,transactionId,recipientUserId,subject,body,status,idempotencyKey,createdBy) VALUES (${input.caseId},${input.transactionId},${input.recipientUserId},${input.subject},${input.body},'sent',${input.idempotencyKey},${ctx.user.id})`); await log(database, ctx.user.id, "due_diligence_request_sent", { transactionId: input.transactionId, idempotencyKey: input.idempotencyKey }); return { requestId: Number(result.insertId), reused: false }; }),
  respondDueDiligenceRequest: protectedProcedure.input(z.object({ requestId: z.number().int(), responseBody: z.string().min(10) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const request = (await rows(database, sql`SELECT transactionId,recipientUserId FROM naqla3_due_diligence_requests WHERE id=${input.requestId} LIMIT 1`))[0]; if (!request || Number(request.recipientUserId) !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN" }); await participant(database, Number(request.transactionId), ctx.user.id, "respond_due_diligence"); await header(database, sql`UPDATE naqla3_due_diligence_requests SET responseBody=${input.responseBody},status='responded' WHERE id=${input.requestId}`); return { status: "responded" }; }),
  completeDueDiligence: protectedProcedure.input(z.object({ caseId: z.number().int(), transactionId: z.number().int(), confirmationNote: z.string().min(8) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await participant(database, input.transactionId, ctx.user.id, "manage_due_diligence"); const pending = await rows(database, sql`SELECT id FROM naqla3_due_diligence_requests WHERE caseId=${input.caseId} AND status NOT IN ('responded','accepted','rejected')`); if (pending.length) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "DUE_DILIGENCE_REQUESTS_PENDING" }); await header(database, sql`UPDATE naqla3_due_diligence_cases SET status='completed',completionNote=${input.confirmationNote},completedBy=${ctx.user.id},completedAt=${now()} WHERE id=${input.caseId} AND transactionId=${input.transactionId}`); return { status: "completed" }; }),
  registerDataRoomDocument: protectedProcedure.input(z.object({ transactionId: z.number().int(), documentType: z.string().min(2).max(80), title: z.string().min(3).max(500), storageKey: z.string().min(3).max(1024), mimeType: z.string().min(3).max(160), sizeBytes: z.number().int().positive(), classification: z.enum(["restricted", "confidential"]) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const access = await participant(database, input.transactionId, ctx.user.id, "manage_data_room"); const result = await header(database, sql`INSERT INTO naqla3_data_room_documents (transactionId,tenantId,documentType,title,storageKey,mimeType,sizeBytes,classification,createdBy) VALUES (${input.transactionId},${access.active.organizationId},${input.documentType},${input.title},${input.storageKey},${input.mimeType},${input.sizeBytes},${input.classification},${ctx.user.id})`); const documentId = Number(result.insertId); await log(database, ctx.user.id, "data_room_document_registered", { transactionId: input.transactionId, metadata: { documentId, documentType: input.documentType } }); return { documentId }; }),
  shareDataRoomDocument: protectedProcedure.input(z.object({ documentId: z.number().int(), granteeUserId: z.number().int(), granteeOrganizationId: z.number().int(), allowedRoles: z.array(z.string().min(2)).min(1).max(10) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const document = (await rows(database, sql`SELECT transactionId FROM naqla3_data_room_documents WHERE id=${input.documentId} AND status='active' LIMIT 1`))[0]; if (!document) throw new TRPCError({ code: "NOT_FOUND" }); await participant(database, Number(document.transactionId), ctx.user.id, "manage_data_room"); await header(database, sql`INSERT INTO naqla3_data_room_document_shares (documentId,granteeUserId,granteeOrganizationId,allowedRoles,status,createdBy) VALUES (${input.documentId},${input.granteeUserId},${input.granteeOrganizationId},${JSON.stringify(input.allowedRoles)},'active',${ctx.user.id}) ON DUPLICATE KEY UPDATE allowedRoles=VALUES(allowedRoles),status='active',revokedAt=NULL,createdBy=VALUES(createdBy)`); await log(database, ctx.user.id, "data_room_document_shared", { transactionId: Number(document.transactionId), metadata: { documentId: input.documentId, granteeUserId: input.granteeUserId } }); return { success: true }; }),
  revokeDataRoomDocumentShare: protectedProcedure.input(z.object({ documentId: z.number().int(), granteeUserId: z.number().int(), granteeOrganizationId: z.number().int() }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const document = (await rows(database, sql`SELECT transactionId FROM naqla3_data_room_documents WHERE id=${input.documentId} LIMIT 1`))[0]; if (!document) throw new TRPCError({ code: "NOT_FOUND" }); await participant(database, Number(document.transactionId), ctx.user.id, "manage_data_room"); await header(database, sql`UPDATE naqla3_data_room_document_shares SET status='revoked',revokedAt=${now()} WHERE documentId=${input.documentId} AND granteeUserId=${input.granteeUserId} AND granteeOrganizationId=${input.granteeOrganizationId}`); await log(database, ctx.user.id, "data_room_share_revoked", { transactionId: Number(document.transactionId), metadata: { documentId: input.documentId, granteeUserId: input.granteeUserId } }); return { success: true }; }),
  listDataRoomDocuments: protectedProcedure.input(z.object({ transactionId: z.number().int() }).strict()).query(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const access = await participant(database, input.transactionId, ctx.user.id, "access_data_room"); const role = String(access.entry.role); const docs = await rows(database, sql`SELECT d.id,d.documentType,d.title,d.mimeType,d.sizeBytes,d.classification,d.createdAt FROM naqla3_data_room_documents d INNER JOIN naqla3_data_room_document_shares s ON s.documentId=d.id WHERE d.transactionId=${input.transactionId} AND d.status='active' AND s.granteeUserId=${ctx.user.id} AND s.granteeOrganizationId=${access.active.organizationId} AND s.status='active' AND JSON_CONTAINS(s.allowedRoles, JSON_QUOTE(${role}))`); if (docs.length) await header(database, sql`INSERT INTO naqla3_disclosure_records (transactionId,documentId,actorUserId,action) SELECT ${input.transactionId},id,${ctx.user.id},'listed' FROM naqla3_data_room_documents WHERE transactionId=${input.transactionId} AND id IN (${sql.join(docs.map(d => sql`${Number(d.id)}`), sql`,`)})`); return docs; }),
  listManagedDataRoomDocuments: protectedProcedure.input(z.object({ transactionId: z.number().int() }).strict()).query(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await participant(database, input.transactionId, ctx.user.id, "manage_data_room"); return rows(database, sql`SELECT id,documentType,title,mimeType,sizeBytes,classification,status,createdAt FROM naqla3_data_room_documents WHERE transactionId=${input.transactionId} ORDER BY id DESC`); }),
  createTermSheet: protectedProcedure.input(z.object({ transactionId: z.number().int(), commercialScope: z.string().min(10).max(12000), structure: z.string().min(10).max(12000) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await participant(database, input.transactionId, ctx.user.id, "manage_due_diligence"); const result = await header(database, sql`INSERT INTO naqla3_term_sheets (transactionId,status,versionNumber,body,createdBy) VALUES (${input.transactionId},'draft',1,${JSON.stringify({ commercialScope: input.commercialScope, structure: input.structure })},${ctx.user.id})`); await log(database, ctx.user.id, "term_sheet_created", { transactionId: input.transactionId }); return { termSheetId: Number(result.insertId), status: "draft" }; }),
  createAgreementRecord: protectedProcedure.input(z.object({ transactionId: z.number().int(), termSheetId: z.number().int(), title: z.string().min(3).max(500) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await participant(database, input.transactionId, ctx.user.id, "manage_due_diligence"); const result = await header(database, sql`INSERT INTO naqla3_agreement_records (transactionId,termSheetId,title,status,createdBy) VALUES (${input.transactionId},${input.termSheetId},${input.title},'draft',${ctx.user.id})`); await log(database, ctx.user.id, "agreement_record_created", { transactionId: input.transactionId }); return { agreementId: Number(result.insertId), status: "draft" }; }),
  setAgreementExecutionStatus: protectedProcedure.input(z.object({ agreementId: z.number().int(), status: z.enum(["executed", "withdrawn"]), externalReference: z.string().trim().min(3).max(256).optional() }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const agreement = (await rows(database, sql`SELECT transactionId FROM naqla3_agreement_records WHERE id=${input.agreementId} LIMIT 1`))[0]; if (!agreement) throw new TRPCError({ code: "NOT_FOUND" }); await participant(database, Number(agreement.transactionId), ctx.user.id, "manage_due_diligence"); await header(database, sql`UPDATE naqla3_agreement_records SET status=${input.status},externalReference=${input.externalReference ?? null},executedAt=${input.status === "executed" ? now() : null} WHERE id=${input.agreementId}`); await log(database, ctx.user.id, "agreement_execution_status", { transactionId: Number(agreement.transactionId), metadata: { agreementId: input.agreementId, status: input.status } }); return { status: input.status }; }),
  createExecutionPlan: protectedProcedure.input(z.object({ transactionId: z.number().int(), objectives: z.string().min(10).max(12000) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await participant(database, input.transactionId, ctx.user.id, "manage_execution"); const result = await header(database, sql`INSERT INTO naqla3_execution_plans (transactionId,objectives,status,createdBy) VALUES (${input.transactionId},${input.objectives},'active',${ctx.user.id})`); await log(database, ctx.user.id, "execution_plan_created", { transactionId: input.transactionId }); return { executionPlanId: Number(result.insertId), status: "active" }; }),
  recordScaleDecision: protectedProcedure.input(z.object({ transactionId: z.number().int(), outcome: z.enum(["continue_limited", "scale", "close"]), lessonsLearned: z.string().trim().min(6).max(12000) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await participant(database, input.transactionId, ctx.user.id, "close_transaction"); const result = await header(database, sql`INSERT INTO naqla3_scale_decisions (transactionId,outcome,lessonsLearned,createdBy) VALUES (${input.transactionId},${input.outcome},${input.lessonsLearned},${ctx.user.id})`); await log(database, ctx.user.id, "scale_decision_recorded", { transactionId: input.transactionId, metadata: { outcome: input.outcome } }); return { decisionId: Number(result.insertId), outcome: input.outcome }; }),
  transitionStage: protectedProcedure.input(z.object({ transactionId: z.number().int(), toStage: z.enum(stages), expectedTransitionVersion: z.number().int().positive(), idempotencyKey: z.string().min(12) }).strict()).mutation(async ({ ctx, input }) => { const database = await getDb(); if (!database) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await participant(database, input.transactionId, ctx.user.id, "manage_asset"); const transaction = (await rows(database, sql`SELECT stage,transitionVersion FROM naqla3_commercial_transactions WHERE id=${input.transactionId} LIMIT 1`))[0]; if (!transaction || Number(transaction.transitionVersion) !== input.expectedTransitionVersion) throw new TRPCError({ code: "CONFLICT", message: "COMMERCIAL_TRANSITION_VERSION_CONFLICT" }); requireNext(String(transaction.stage), input.toStage); if (input.toStage === "contract") { const complete = (await rows(database, sql`SELECT id FROM naqla3_due_diligence_cases WHERE transactionId=${input.transactionId} AND status='completed' LIMIT 1`))[0]; if (!complete) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "DUE_DILIGENCE_COMPLETION_REQUIRED" }); } if (input.toStage === "execute") { const agreement = (await rows(database, sql`SELECT id FROM naqla3_agreement_records WHERE transactionId=${input.transactionId} AND status='executed' LIMIT 1`))[0]; if (!agreement) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "EXECUTED_AGREEMENT_REQUIRED" }); } if (input.toStage === "scale") { const plan = (await rows(database, sql`SELECT id FROM naqla3_execution_plans WHERE transactionId=${input.transactionId} AND status='active' LIMIT 1`))[0]; if (!plan) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "EXECUTION_PLAN_REQUIRED" }); } await header(database, sql`UPDATE naqla3_commercial_transactions SET stage=${input.toStage},transitionVersion=transitionVersion+1 WHERE id=${input.transactionId}`); await log(database, ctx.user.id, "stage_transition", { transactionId: input.transactionId, idempotencyKey: input.idempotencyKey, metadata: { toStage: input.toStage } }); return { stage: input.toStage, transitionVersion: input.expectedTransitionVersion + 1 }; }),
});
